import { useState } from 'react'
import './App.css'

function App() {
  const [count, setCount] = useState(0)

  return (
    <div className="app-container">
      <header className="hero">
        <h1>React to BWEB Compiler</h1>
        <p>This UI was built in React, compiled via Vite, and exported as a single BWEB binary!</p>
        <button className="primary-btn" onClick={() => setCount((count) => count + 1)}>
          React state count is {count}
        </button>
      </header>

      <main className="gallery">
        <h2>Features</h2>
        <div className="grid">
          <div className="card">
            <h3>Zero JS Framework Overhead</h3>
            <p>Once compiled, the viewer doesn't need to load the massive React library.</p>
          </div>
          <div className="card">
            <h3>Pixel Perfect</h3>
            <p>BWEB captures the exact DOM layout generated by React.</p>
          </div>
          <div className="card">
            <h3>Vite Ecosystem</h3>
            <p>Use any PostCSS, Tailwind, or Vite plugin during build!</p>
          </div>
        </div>
      </main>
    </div>
  )
}

export default App
